<?php

namespace AppBundle\Repository;

/**
 * ev_addressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ev_addressRepository extends \Doctrine\ORM\EntityRepository
{
}
